spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://gryoh.synology.me:3306/yummy?serverTimezone=UTC&characterEncoding=UTF-8
    username: yummy
    password: 1q2w3e4r5T!
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE